name: PR Artifact Android

on:
  pull_request:
    branches: [main]
    paths-ignore: [docs/**, doxygen_doc/**, lgtm/**, utilities/**, scripts/**, "**.md", "**.mdx"]
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pr-artifact-android-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version-label: pr-${{ github.event.pull_request.number || github.run_id }}
      mode: release
      matrix-json: |
        [
          { "name": "Android ARM64", "platform": "android", "artifact": "android-x64", "os": "ubuntu-latest", "android": "arm64", "tiles": true, "ext": "apk", "content-type": "application/apk" }
        ]
      download-translations: false
      package-artifacts: true
      run-tests: false
      android-localize: false
      upload-artifacts: true
